apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./base/namespace.yaml
  - ./base/ingress-kind.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.6/manifests/install.yaml

namespace: argocd

patches:
  - path: patches/extension.yaml
  - path: patches/argocd-cm.yaml
  - path: patches/argocd-rbac-cm.yaml
