apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-events
  namespace: argo-events
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: argo-events-192.168.0.100.nip.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: events-webhook
            port:
              number: 443
